# Generated by Django 3.1 on 2020-08-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
