# Generated by Django 3.1 on 2020-08-22 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_choice', models.CharField(choices=[('1-5', 'First to Fifth'), ('6-8', 'Sixth to Eigth'), ('9-10', 'Ninth to Tenth'), ('11-12', 'Eleventh to Twelfth'), ('9-12', 'Ninth to Twelfth')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('experience', models.DecimalField(decimal_places=2, max_digits=4)),
                ('photo', models.ImageField(upload_to='teachers')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.classes')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.location')),
            ],
        ),
    ]
