# Generated by Django 3.1 on 2020-08-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_classes_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.CharField(choices=[('1-5', 'First to Fifth'), ('6-8', 'Sixth to Eigth'), ('9-10', 'Ninth to Tenth'), ('11-12', 'Eleventh to Twelfth'), ('9-12', 'Ninth to Twelfth')], max_length=6),
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
    ]
