# Generated by Django 3.1 on 2020-08-23 08:21

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20200823_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact Phone Number', max_length=31),
        ),
    ]
