# Generated by Django 3.1 on 2020-08-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_teacher_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='number',
            new_name='phone',
        ),
    ]
