# Generated by Django 3.1 on 2020-08-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_teacher_teacher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
