# Generated by Django 3.1 on 2020-08-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_teacher_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject1',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject2',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject3',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
