# Generated by Django 3.1 on 2020-08-27 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_auto_20200827_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='location',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject1',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject2',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject3',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
