# Generated by Django 3.1 on 2020-08-27 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_subject_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject1',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject2',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subject3',
        ),
    ]
