# Generated by Django 3.1 on 2020-08-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0020_auto_20200827_1335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
