# Generated by Django 3.1 on 2020-08-27 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0021_delete_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject1', to='Home.subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject2', to='Home.subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject3', to='Home.subject'),
        ),
    ]
