# Generated by Django 3.1 on 2020-08-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_auto_20200827_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classes',
            field=models.CharField(choices=[('1-5', 'First to Fifth'), ('6-8', 'Sixth to Eighth'), ('9-10', 'Ninth to Tenth'), ('11-12', 'Eleventh to Twelfth')], max_length=6),
        ),
    ]
